#!/usr/bin/env python3
import os
import json
import subprocess
from datetime import datetime
import xml.etree.ElementTree as ET
from xml.dom import minidom

# Configuration
DOMAIN = "https://www.techm4india.com"
SITEMAP_FILE = "sitemap.xml"
VERCEL_JSON = "vercel.json"

# Priority & Changefreq mapping based on route path
PRIORITY_MAP = {
    "/": "1.0",
    "/engineering": "0.9",
    "/solutions": "0.9",
    "/space": "0.9",
    "/schools": "0.9",
    "/about": "0.8",
    "/programs": "0.8",
    "/research": "0.8",
    "/ecosystem": "0.8",
    "/impact": "0.7",
    "/vision": "0.7",
    "/careers": "0.7",
    "/contact": "0.6"
}

CHANGEFREQ_MAP = {
    "/": "weekly",
    "/engineering": "weekly",
    "/solutions": "weekly",
    "/space": "weekly",
    "/schools": "weekly",
    "/about": "monthly",
    "/programs": "weekly",
    "/research": "monthly",
    "/ecosystem": "monthly",
    "/impact": "monthly",
    "/vision": "monthly",
    "/careers": "weekly",
    "/contact": "monthly"
}

def get_last_modified_date(filepath):
    # Try to get date from git log
    try:
        cmd = ["git", "log", "-1", "--format=%cs", "--", filepath]
        output = subprocess.check_output(cmd, stderr=subprocess.DEVNULL).decode().strip()
        if output:
            return output
    except Exception:
        pass
    
    # Fallback to filesystem modification date
    try:
        mtime = os.path.getmtime(filepath)
        return datetime.fromtimestamp(mtime).strftime("%Y-%m-%d")
    except Exception:
        return datetime.now().strftime("%Y-%m-%d")

def generate_sitemap():
    if not os.path.exists(VERCEL_JSON):
        print(f"Error: {VERCEL_JSON} not found!")
        return

    with open(VERCEL_JSON, 'r') as f:
        config = json.load(f)

    routes = config.get("routes", [])
    urls = []

    for route in routes:
        src = route.get("src")
        dest = route.get("dest")

        # Skip wildcard patterns, files that aren't html, or invalid routes
        if src.startswith("/(.*)") or not dest or not dest.endswith(".html"):
            continue

        # Clean the file path (remove leading slash)
        filepath = dest.lstrip("/")

        # Check if the file actually exists
        if not os.path.exists(filepath):
            print(f"Warning: File {filepath} for route {src} not found. Skipping.")
            continue

        lastmod = get_last_modified_date(filepath)
        priority = PRIORITY_MAP.get(src, "0.5")
        changefreq = CHANGEFREQ_MAP.get(src, "monthly")

        # Handle home page path mapping
        url_path = "" if src == "/" else src

        urls.append({
            "loc": f"{DOMAIN}{url_path}",
            "lastmod": lastmod,
            "changefreq": changefreq,
            "priority": priority
        })

    # Build XML
    urlset = ET.Element("urlset", {
        "xmlns": "http://www.sitemaps.org/schemas/sitemap/0.9",
        "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "xsi:schemaLocation": "http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"
    })

    for item in urls:
        url = ET.SubElement(urlset, "url")
        ET.SubElement(url, "loc").text = item["loc"]
        ET.SubElement(url, "lastmod").text = item["lastmod"]
        ET.SubElement(url, "changefreq").text = item["changefreq"]
        ET.SubElement(url, "priority").text = item["priority"]

    # Pretty print XML
    raw_xml = ET.tostring(urlset, encoding="utf-8")
    parsed_xml = minidom.parseString(raw_xml)
    pretty_xml = parsed_xml.toprettyxml(indent="  ", encoding="utf-8").decode("utf-8")

    # Clean up duplicate empty lines/header formatting generated by minidom
    lines = [line for line in pretty_xml.splitlines() if line.strip()]
    cleaned_xml = '\n'.join(lines) + '\n'

    # Remove standard xml declaration duplicate and write
    with open(SITEMAP_FILE, 'w', encoding='utf-8') as f:
        f.write(cleaned_xml)

    print(f"Successfully generated {SITEMAP_FILE} with {len(urls)} URLs.")

if __name__ == "__main__":
    generate_sitemap()
