name: Sync to Deploy Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Target Repo
        run: |
          git remote add target https://x-access-token:${{ secrets.SYNC_PAT }}@github.com/techm4india/techm4india.github.io.git
          git push -f target main
